{
  "openapi": "3.0.1",
  "info": {
    "title": "Nerdcave API",
    "description": "",
    "version": "1.0.0"
  },
  "externalDocs": {
    "description": "Find out more about Swagger",
    "url": "http://swagger.io"
  },
  "servers": [
    {
      "url": "https://www.nerdcave.club/api"
    },
    {
      "url": "http://localhost:8080/api"
    }
  ],
  "tags": [
    {
      "name": "login",
      "description": "Login operation"
    },
    {
      "name": "member",
      "description": "Member info"
    },
    {
      "name": "product",
      "description": "nerdcave product"
    },
    {
      "name": "payment",
      "description": "wechat payment"
    },
    {
      "name": "offlineorder",
      "description": "线下订单"
    },
    {
      "name": "branch",
      "description": "分店信息"
    },
    {
      "name": "checkIn",
      "description": "用户打卡"
    },
    {
      "name": "disclaimer",
      "description": "memeber disclaimer"
    }
  ],
  "paths": {
    "/login": {
      "post": {
        "tags": [
          "login"
        ],
        "summary": "Login with wx code",
        "operationId": "login",
        "requestBody": {
          "description": "Login with wx code",
          "content": {
            "application/json": {
              "schema": {
                "$ref": "#/components/schemas/WXInfo"
              }
            }
          },
          "required": true
        },
        "responses": {
          "200": {
            "description": "successful login",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/Member"
                },
                "examples": {
                  "NormalMember": {
                    "value": {
                      "memberType": "NORMAL",
                      "memberDetail": {
                        "memberType": "NORMAL",
                        "remainingEntries": 10
                      }
                    }
                  },
                  "YearlyMember": {
                    "value": {
                      "memberType": "YEARLY",
                      "memberDetail": {
                        "memberType": "YEARLY",
                        "expiryDate": "20210228"
                      }
                    }
                  },
                  "MonthlyMember": {
                    "value": {
                      "memberType": "MONTHLY",
                      "memberDetail": {
                        "memberType": "MONTHLY",
                        "expiryDate": "20210228"
                      }
                    }
                  }
                }
              }
            }
          },
          "400": {
            "description": "error thrown when calling WX api",
            "content": {
              "text/plain": {
                "schema": {
                  "type": "string"
                }
              }
            }
          }
        },
        "x-codegen-request-body-name": "body"
      }
    },
    "/member/info": {
      "get": {
        "tags": [
          "member"
        ],
        "summary": "Get member info",
        "operationId": "member info",
        "responses": {
          "200": {
            "description": "ok",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/Member"
                },
                "examples": {
                  "NormalMember": {
                    "value": {
                      "memberType": "NORMAL",
                      "memberDetail": {
                        "memberType": "NORMAL",
                        "remainingEntries": 1
                      }
                    }
                  },
                  "MultiEntriesMember": {
                    "value": {
                      "memberType": "MULTI_ENTRIES",
                      "memberDetail": {
                        "memberType": "MULTI_ENTRIES",
                        "usedEntries": 1,
                        "totalEntries": 10,
                        "validFrom": "20200101",
                        "validUntil": "20200301"
                      }
                    }
                  },
                  "YearlyMember": {
                    "value": {
                      "memberType": "YEARLY",
                      "memberDetail": {
                        "memberType": "YEARLY",
                        "validFrom": "20200101",
                        "validUntil": "20201231"
                      }
                    }
                  },
                  "MonthlyMember": {
                    "value": {
                      "memberType": "MONTHLY",
                      "memberDetail": {
                        "memberType": "MONTHLY",
                        "validFrom": "20200101",
                        "validUntil": "20200131"
                      }
                    }
                  }
                }
              }
            }
          },
          "401": {
            "description": "Unauthorized"
          }
        }
      }
    },
    "/product/all": {
      "get": {
        "tags": [
          "product"
        ],
        "summary": "All nerdcave products",
        "operationId": "allProducts",
        "responses": {
          "200": {
            "description": "ok",
            "content": {
              "application/json": {
                "schema": {
                  "type": "array",
                  "items": {
                    "$ref": "#/components/schemas/Produt"
                  }
                },
                "examples": {
                  "MULTI_ENTRIES_FEE": {
                    "value": {
                      "id": "123",
                      "productType": "MULTI_ENTRIES_FEE",
                      "detail": {
                        "productType": "MULTI_ENTRIES_FEE",
                        "entries": "10,",
                        "validMonths": 3
                      },
                      "description": "Product-1 10 entries",
                      "regularPrice": 200,
                      "fee": 200,
                      "discounts": [],
                      "payViaWechat": false,
                      "enabled": true
                    }
                  },
                  "EQUIPMENT_RENTAL_FEE": {
                    "value": {
                      "id": "234",
                      "productType": "EQUIPMENT_RENTAL_FEE",
                      "detail": {
                        "productType": "EQUIPMENT_RENTAL_FEE"
                      },
                      "description": "Boot rentail",
                      "regularPrice": 1,
                      "fee": 1,
                      "discounts": [],
                      "payViaWechat": true,
                      "enabled": true
                    }
                  },
                  "MONTHLY_MEMBER_FEE": {
                    "value": {
                      "id": "456",
                      "productType": "MONTHLY_MEMBER_FEE",
                      "detail": {
                        "productType": "MONTHLY_MEMBER_FEE",
                        "months": 1
                      },
                      "description": "Product-2 1 month",
                      "regularPrice": 400,
                      "fee": 400,
                      "discounts": [],
                      "payViaWechat": false,
                      "enabled": true
                    }
                  },
                  "YEARLY_MEMBER_FEE": {
                    "value": {
                      "id": "789",
                      "productType": "YEARLY_MEMBER_FEE",
                      "detail": {
                        "productType": "YEARLY_MEMBER_FEE",
                        "years": 1
                      },
                      "description": "Product-3 1 year",
                      "regularPrice": 600,
                      "fee": 600,
                      "discounts": [],
                      "payViaWechat": false,
                      "enabled": true
                    }
                  },
                  "SINGLE_ENTRY_FEE": {
                    "value": {
                      "id": "890",
                      "productType": "SINGLE_ENTRY_FEE",
                      "detail": {
                        "productType": "SINGLE_ENTRY_FEE"
                      },
                      "description": "Single entry",
                      "regularPrice": 200,
                      "fee": 1,
                      "discounts": [
                        {
                          "discountType": "WEEK_DAY",
                          "description": "0.01 \"CNY weekday discount\"",
                          "detail": {
                            "discountType": "WEEK_DAY",
                            "salePrice": 1
                          }
                        }
                      ],
                      "payViaWechat": true,
                      "enabled": true
                    }
                  }
                }
              }
            }
          }
        }
      }
    },
    "/payment/placeOrder": {
      "post": {
        "tags": [
          "payment"
        ],
        "summary": "Place order",
        "description": "This can only be done by the logged in user.",
        "operationId": "placeOrder",
        "requestBody": {
          "description": "Place order",
          "content": {
            "*/*": {
              "schema": {
                "$ref": "#/components/schemas/WXOrder"
              }
            }
          },
          "required": true
        },
        "responses": {
          "200": {
            "description": "ok",
            "content": {
              "application/json": {
                "schema": {
                  "type": "object"
                }
              }
            }
          }
        },
        "x-codegen-request-body-name": "body"
      }
    },
    "/payment/info/{paymentId}": {
      "get": {
        "tags": [
          "payment"
        ],
        "summary": "Fetch payment",
        "description": "This can only be done by the logged in user.",
        "operationId": "Fetch Payment",
        "parameters": [
          {
            "name": "paymentId",
            "in": "path",
            "description": "Payment Id",
            "required": true,
            "schema": {
              "type": "string"
            }
          }
        ],
        "responses": {
          "200": {
            "description": "successful operation",
            "content": {
              "application/json": {
                "schema": {
                  "type": "object"
                }
              }
            }
          }
        }
      }
    },
    "/offlineorder/placeOrder": {
      "post": {
        "tags": [
          "offlineorder"
        ],
        "summary": "place offline order",
        "description": "This can only be done by the logged in user.",
        "operationId": "Place Offline Order",
        "requestBody": {
          "description": "Place order",
          "content": {
            "*/*": {
              "schema": {
                "$ref": "#/components/schemas/OfflineOrder"
              }
            }
          },
          "required": true
        },
        "responses": {
          "200": {
            "description": "ok",
            "content": {
              "application/json": {
                "schema": {
                  "type": "object"
                }
              }
            }
          }
        },
        "x-codegen-request-body-name": "body"
      }
    },
    "/checkIn": {
      "post": {
        "tags": [
          "checkIn"
        ],
        "summary": "Member check in",
        "description": "用户一天只能打卡一次, 请先调用/checkIn/token查询",
        "operationId": "Member Check In",
        "requestBody": {
          "description": "打卡",
          "content": {
            "*/*": {
              "schema": {
                "$ref": "#/components/schemas/CheckInBody"
              }
            }
          },
          "required": true
        },
        "responses": {
          "200": {
            "description": "ok",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/CheckInToken"
                },
                "example": {
                  "checkInNumber": "2021",
                  "hasEquipment": false
                }
              }
            }
          },
          "400": {
            "description": "No ticket"
          }
        }
      }
    },
    "/checkIn/token/{date}": {
      "get": {
        "tags": [
          "checkIn"
        ],
        "summary": "Check member check-in token",
        "description": "查询用户打卡号",
        "parameters": [
          {
            "name": "date",
            "in": "path",
            "description": "date",
            "required": true,
            "example": "20200220",
            "schema": {
              "type": "string"
            }
          }
        ],
        "responses": {
          "200": {
            "description": "ok",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/CheckInToken"
                },
                "example": {
                  "checkInNumber": "2021",
                  "hasEquipment": false
                }
              }
            }
          },
          "404": {
            "description": "not found"
          }
        }
      }
    },
    "/checkIn/history/{startDate}": {
      "get": {
        "tags": [
          "checkIn"
        ],
        "summary": "Member check in history from startDate(inclusive)",
        "description": "This can only be done by the logged in user.",
        "operationId": "Member Check In History",
        "parameters": [
          {
            "name": "startDate",
            "in": "path",
            "description": "start date inclusive",
            "required": true,
            "example": "20200220",
            "schema": {
              "type": "string"
            }
          }
        ],
        "responses": {
          "200": {
            "description": "ok",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/ArrayOfDate"
                },
                "example": [
                  "20200227",
                  "20200228"
                ]
              }
            }
          }
        }
      }
    },
    "/checkIn/history/{startDate}/{endDate}": {
      "get": {
        "tags": [
          "checkIn"
        ],
        "summary": "Member check in history from startDate(inclusive) to endDate(exclusive)",
        "description": "This can only be done by the logged in user.",
        "operationId": "Member Check In History to endDate",
        "parameters": [
          {
            "name": "startDate",
            "in": "path",
            "description": "start date inclusive",
            "required": true,
            "example": "20200220",
            "schema": {
              "type": "string"
            }
          },
          {
            "name": "endDate",
            "in": "path",
            "description": "start date exclusive",
            "required": true,
            "example": "20200301",
            "schema": {
              "type": "string"
            }
          }
        ],
        "responses": {
          "200": {
            "description": "ok",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/ArrayOfDate"
                },
                "example": [
                  "20200227",
                  "20200228"
                ]
              }
            }
          }
        }
      }
    },
    "/branch/all": {
      "get": {
        "tags": [
          "branch"
        ],
        "summary": "All nerdcave branches",
        "operationId": "allBranches",
        "responses": {
          "200": {
            "description": "ok",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/BranchClientInfo"
                }
              }
            }
          }
        }
      }
    },
    "/branch": {
      "post": {
        "tags": [
          "branch"
        ],
        "summary": "Create nerdcave branch",
        "operationId": "createBranch",
        "requestBody": {
          "description": "branch information",
          "content": {
            "application/json": {
              "schema": {
                "$ref": "#/components/schemas/Branch"
              }
            }
          }
        },
        "responses": {
          "201": {
            "description": "Created",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/Id"
                }
              }
            }
          },
          "401": {
            "description": "Unauthorized",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/Error"
                }
              }
            }
          }
        }
      }
    },
    "/branch/{branchId}": {
      "get": {
        "tags": [
          "branch"
        ],
        "summary": "Get branch by id",
        "operationId": "branchById",
        "parameters": [
          {
            "name": "branchId",
            "in": "path",
            "description": "Branch Id",
            "required": true,
            "schema": {
              "type": "string"
            }
          }
        ],
        "responses": {
          "200": {
            "description": "ok",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/BranchClientInfo"
                }
              }
            }
          },
          "404": {
            "description": "Not found"
          }
        }
      }
    },
    "/disclaimer/hasSigned": {
      "get": {
        "tags": [
          "disclaimer"
        ],
        "summary": "Check whether member has signed disclaimer",
        "operationId": "signed disclaimer",
        "responses": {
          "200": {
            "description": "ok",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/SignedBody"
                },
                "example": {
                  "signed": true
                }
              }
            }
          }
        }
      }
    },
    "/disclaimer/sign": {
      "post": {
        "tags": [
          "disclaimer"
        ],
        "requestBody": {
          "description": "打卡",
          "content": {
            "*/*": {
              "schema": {
                "$ref": "#/components/schemas/DisclaimerBody"
              }
            }
          },
          "required": true
        },
        "responses": {
          "200": {
            "description": "ok",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/Ok"
                },
                "example": {
                  "ok": 1
                }
              }
            }
          }
        }
      }
    }
  },
  "components": {
    "schemas": {
      "Id": {
        "type": "object",
        "properties": {
          "id": {
            "type": "string"
          }
        },
        "required": [
          "id"
        ]
      },
      "ProductDiscount": {
        "type": "object",
        "properties": {
          "discountType": {
            "type": "string",
            "enum": [
              "WEEK_DAY"
            ]
          },
          "description": {
            "type": "string"
          },
          "detail": {
            "type": "object"
          }
        }
      },
      "Produt": {
        "type": "object",
        "properties": {
          "id": {
            "type": "string"
          },
          "productType": {
            "type": "string",
            "enum": [
              "MULTI_ENTRIES_FEE",
              "MONTHLY_MEMBER_FEE",
              "YEARLY_MEMBER_FEE",
              "SINGLE_ENTRY_FEE",
              "EQUIPMENT_RENTAL_FEE"
            ]
          },
          "detail": {
            "type": "object"
          },
          "shortDescription": {
            "type": "string"
          },
          "description": {
            "type": "string"
          },
          "discounts": {
            "type": "array",
            "items": {
              "$ref": "#/components/schemas/ProductDiscount"
            }
          }
        }
      },
      "OfflineOrder": {
        "type": "object",
        "properties": {
          "branchId": {
            "type": "string"
          },
          "productId": {
            "type": "string"
          }
        }
      },
      "WXOrder": {
        "type": "object",
        "properties": {
          "branchId": {
            "type": "string"
          },
          "products": {
            "type": "array",
            "items": {
              "type": "string"
            }
          }
        }
      },
      "WXInfo": {
        "type": "object",
        "properties": {
          "code": {
            "type": "string"
          },
          "nickName": {
            "type": "string"
          },
          "gender": {
            "type": "string"
          }
        }
      },
      "Member": {
        "type": "object",
        "properties": {
          "memberType": {
            "type": "string",
            "enum": [
              "NORMAL",
              "MONTHLY",
              "YEARLY"
            ]
          },
          "memberDetail": {
            "type": "object",
            "properties": {}
          }
        }
      },
      "Location": {
        "type": "object",
        "properties": {
          "longitude": {
            "type": "number"
          },
          "latitude": {
            "type": "number"
          },
          "description": {
            "type": "string"
          }
        },
        "required": [
          "longitude",
          "latitude",
          "description"
        ]
      },
      "OpenHour": {
        "type": "object",
        "properties": {
          "openTime": {
            "type": "string",
            "format": "HHmmss"
          },
          "closeTime": {
            "type": "string",
            "format": "HHmmss"
          },
          "description": {
            "type": "string"
          }
        },
        "required": [
          "openTime",
          "closeTime",
          "description"
        ]
      },
      "BranchClientInfo": {
        "type": "object",
        "properties": {
          "id": {
            "type": "string",
            "description": "No need for branch creation"
          },
          "name": {
            "type": "string"
          },
          "location": {
            "$ref": "#/components/schemas/Location"
          },
          "weekdayOpenHour": {
            "$ref": "#/components/schemas/OpenHour"
          },
          "weekendOpenHour": {
            "$ref": "#/components/schemas/OpenHour"
          },
          "contactNumbers": {
            "type": "array",
            "items": {
              "type": "string"
            }
          },
          "description": {
            "type": "string"
          },
          "isOpen": {
            "type": "boolean"
          }
        }
      },
      "Branch": {
        "type": "object",
        "properties": {
          "id": {
            "type": "string",
            "description": "No need for branch creation"
          },
          "location": {
            "$ref": "#/components/schemas/Location"
          },
          "openHour": {
            "$ref": "#/components/schemas/OpenHour"
          },
          "contactNumbers": {
            "type": "array",
            "items": {
              "type": "string"
            }
          },
          "description": {
            "type": "string"
          }
        },
        "required": [
          "location",
          "openHour",
          "contactNumbers",
          "description"
        ]
      },
      "Error": {
        "type": "object",
        "properties": {
          "msg": {
            "type": "string"
          }
        }
      },
      "CheckInToken": {
        "type": "object",
        "properties": {
          "checkInNumber": {
            "type": "string"
          },
          "hasEquipment": {
            "type": "boolean"
          }
        }
      },
      "ArrayOfDate": {
        "type": "array",
        "items": {
          "type": "string"
        }
      },
      "CheckInBody": {
        "type": "object",
        "properties": {
          "branchId": {
            "type": "string"
          }
        }
      },
      "Ok": {
        "type": "object",
        "properties": {
          "ok": {
            "type": "integer"
          }
        }
      },
      "SignedBody": {
        "type": "object",
        "properties": {
          "signed": {
            "type": "boolean"
          }
        }
      },
      "DisclaimerBody": {
        "type": "object",
        "properties": {
          "legalName": {
            "type": "string"
          },
          "contactNumber": {
            "type": "string"
          },
          "emergentContactNumber": {
            "type": "string"
          }
        }
      }
    }
  }
}